name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@64b759fc0e18682ff47a0522072df02762a76af2
        with:
          target_branch: gh-pages
          target_path: /
          jekyll_env: production
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: helaili/jekyll-action@64b759fc0e18682ff47a0522072df02762a76af2
        with:
          target_branch: gh-pages
          target_path: dev
          jekyll_env: development
          token: ${{ secrets.GITHUB_TOKEN }}